const ActionTypes={
    INIT_PHOTOS:"INIT_PHOTOS'",
    UPDATE_PHOTOS:"UPDATE_PHOTOS",
    DELETE_PHOTOS:"DELETE_PHOTOS",
    ADD_PHOTOS:"ADD_PHOTOS",
    ADD_LIKE:"ADD_LIKE",
    REMOVE_LIKE:"REMOVE_LIKE",
    ADD_COMMENT:"ADD_COMMENT",
    REMOVE_COMMENT:"REMOVE_COMMENT",
  

    INIT_USERS:"INIT_USERS",
    ADD_USERS:"ADD_USERS",
    UPDATE_USERS:"UPDATE_USERS",
    DELETE_USERS:"DELETE_USERS",
    ADD_FAVORITE:"ADD_FAVORITE",
    REMOVE_FAVORITE:"REMOVE_FAVORITE",

    NEW_ACTIVITY:"NEW_ACTIVITY",

    LOG_IN:"LOG_IN",
    READ_MESSAGE:"READ_MESSAGE",
    NEW_MESSAGE:"NEW_MESSAGE",

    CLEAR_WHOLE:"CLEAR_WHOLE",
}
export default ActionTypes